github_impact:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: "{{ env_var('WAREHOUSE_DB_USER', 'warehouse') }}"
      password: "{{ env_var('WAREHOUSE_DB_PASSWORD', 'warehouse') }}"
      port: 5432
      dbname: "{{ env_var('WAREHOUSE_DB_NAME', 'github_warehouse') }}"
      schema: marts
      threads: 4
      keepalives_idle: 0
