github_impact:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: warehouse
      password: warehouse
      port: 5432
      dbname: github_warehouse
      schema: marts
      threads: 4
      keepalives_idle: 0
